### PR TITLE
Fixup random interval jittering

### PR DESCRIPTION
**Pull request by sparrc**
@daviesalex This should fix interval jittering to be a completely random distribution

### CODE REVIEW

**Comment by otoolep** [comment]
Is this controllable via config param? Whether it is enabled or not? 

Also, what is the maximum jitter?

**Comment by sparrc** [comment]
@otoolep there is no maximum jitter, and there are two config parameters to control this, these are the defaults:

```
flush_interval = "10s"
flush_jitter = "5s"
```

which means that the flusher will run every 10-15 seconds

**Comment by otoolep** [comment]
OK, good enough. As long as setting `flush_jitter` to `0s` will disable jitter that should be fine. Some people may have reasons for Telegraf to emit exactly periodically.

If you have not done so already, I would add a comment to the config explaining that jitter is about preventing large numbers of Telegraf instances all emitting at the same time, generating big traffic spikes.

**Comment by sparrc** [comment]
@otoolep good idea on the config, I'm also going to add unit tests for this function

**Comment by daviesalex** [comment]
LGTM

**Pull request merged**
