### PR TITLE
Un-break the packaging script.

### PR DESCRIPTION
**Pull request by toddboom**

### CODE REVIEW

**Comment by toddboom** [comment]
@otoolep @evanphx the packaging script was barfing until i yanked this - does it need to be in there?

**Comment by otoolep** [comment]
This was something that was added for the InfluxDB packaging, seemed to work fine there. Not sure why it is having problems with telegraf?

What is the error?

**Comment by toddboom** [comment]
@otoolep something about an invalid call to rpmbuild. it wasn't very helpful.

**Comment by otoolep** [comment]
OK.

It's not critical, you can pull it. We ran without the dependency check for a while.

**Pull request merged**
