### PR TITLE
Multiple Outputs Mark II

### PR DESCRIPTION
**Pull request by jipperinbham**
***NOTE*** 
***BREAKING CHANGE***
Once this is merged, all existing config.toml files will be invalid and need to be updated. All examples in the project have been updated with the new format.

Attempt to move the InfluxDB client into an `outputs` pkg to allow for different outputs in the future. 

@sparrc there's still some merge conflicts but I've done my best to get everything as close to master as possible where I can. Everything has been `go vet`ed and `golint`ed.

### CODE REVIEW

**Comment by pauldix** [comment]
`Output` interface should have a `Close() error` method so Telegraf can be cleanly shut down. Maybe in a separate PR?

I'm cool with the breaking change. Sad we have to make it, but everyone will be better for it :)

**Comment by jipperinbham** [comment]
Good thought on adding `Close()` to the interface. As soon as #109 is merged, I can get that in shortly after. 

I made a few attempts to not make it such a breaking change but couldn't ever settle on a config format that didn't seem like magic.

**Comment by sparrc** [comment]
Closing this PR because it got covered by PR #109, apologies that most of your commits got covered up, the rebasing got a little bit crazy ;-)

Thanks so much @jipperinbham! This is huge!

**Comment by jipperinbham** [comment]
@sparrc thanks for all the help getting this in! Hope to get started on a new output soon.

**Pull request closed without merging**
