### PR TITLE
GOPATH can have multiple : separated paths in it.

### PR DESCRIPTION
**Pull request by gotyaoi**
Couldn't find an easy way to do this in make language. Pretty sure this is sh compatible.

### CODE REVIEW

**Comment by gotyaoi** [comment]
Ah, forgot to mention: the reason that I personally run into this is that I sometimes need to run with

    GOPATH=`godep path\`:$GOPATH

from the godep docs, as some parts of my IDE are not as smart as they should be yet. This will also come up for people who use multiple paths to separate personal code from internet code.

**Comment by sparrc** [comment]
@gotyaoi We could also just require that GOBIN is part of the users PATH to use the makefile.

That way we could just remove all of the GOBIN references and simply execute `godep` directly

**Comment by gotyaoi** [comment]
Possibly. Another possibility would be to add all possible GOBIN directories to the front of the PATH in the makefile. I'll try that out tonight.

**Comment by gotyaoi** [comment]
@sparrc How does that look?

**Comment by sparrc** [comment]
looks good, thanks @gotyaoi

**Pull request closed without merging**
