### PR TITLE
Added Mountpoints and SkipInodeUsage to Disk plugin

### PR DESCRIPTION
**Pull request by subhachandrachandra**
Added Mountpoints and SkipInodeUsage to the Disk plugin to restrict stats reporting to specific mountpoint and make inode stats optional.

### CODE REVIEW

**Comment by sparrc** [comment]
Please remove the SkipInodesUsage option, you can filter these out with the `drop` option, see https://github.com/influxdb/telegraf#plugin-options

this should work:

```
[disk]
    drop = ["disk_inode"]
```

**Comment by sparrc** [comment]
You should also write some unit tests for filtering the mount points.

I know that the current state of the system unit tests is a bit confusing (sorry!), but you should be able to accomplish it by modifying the data structure here: https://github.com/influxdb/telegraf/blob/master/plugins/system/system_test.go#L54-L61

which then gets checked here: https://github.com/influxdb/telegraf/blob/master/plugins/system/system_test.go#L183-L193

**Comment by subhachandrachandra** [comment]
Thanks sparrc. I just figured out the test issue. I will add some tests and resubmit. I will drop the SkipInodeUsage option. Do you think it is worthwhile to add a % option for disk usage? I would normally monitor the %free rather than the absolute values.

**Comment by sparrc** [comment]
@subhachandrachandra that would be okay to add percent for now, but for Telegraf 0.2.0 we may eliminate those. We will putting measurements from the same plugin as fields in a single measurement. 

Meaning you will be able to do something like `SELECT free/used FROM disk` to get percentages.

thanks!

**Pull request closed without merging**
