### PR TITLE
Elasticsearch cluster health

### PR DESCRIPTION
**Pull request by jipperinbham**
addresses https://github.com/influxdb/telegraf/issues/310

### CODE REVIEW

**Comment by otoolep** [comment]
Thanks @jipperinbham 

Can you show us some queries in action, after this data is written to an InfluxDB system by Telegraf?

**Comment by sparrc** [comment]
@jipperinbham just a README would be great, you can give examples from debug/test output

**Comment by jipperinbham** [comment]
image

image

**Comment by otoolep** [comment]
Nice, if GROUP BY works as we discussed, +1 from me.

**Comment by jipperinbham** [comment]
sorry, forgot to paste that one

image

**Comment by jipperinbham** [comment]
@sparrc I'll get a README together for the elasticsearch plugin in a bit

**Comment by sparrc** [comment]
awesome, thank you @jipperinbham!

**Pull request closed without merging**
