### PR TITLE
Add MQTT output.

### PR DESCRIPTION
**Pull request by shirou**
Add output which sends metrics to MQTT server.

The topic format is 
```
<topic_prefix>/host/<hostname>/<pluginname>/<metric_name>
ex: prefix/host/web1.example.com/mem/available
```

`hostname` in a topic is specified in the `outputs.mqtt` config section, not `agent` Because I could not found how to inherit hostname value from agant.

### CODE REVIEW

**Comment by sparrc** [comment]
@shirou you should not have to manually update Godeps.json, try doing this:

```
$ go get github.com/tools/godep
$ godep save ./...
```

**Comment by sparrc** [comment]
@shirou thank you for the contribution! :+1: You shouldn't need to inherit the hostname tag, the agent should add that tag automatically in addition to the ones you add within this plugin

**Comment by shirou** [comment]
@sparrc Thank you for the comments. I type
```
godep restore
godep save ./...
```
Then, the other packages are also updated. If I made a mistake, I will revert it.

And, Thank you for the suggestion about hostname. I removed the settings in the MQTT section.

**Comment by sparrc** [comment]
Thanks @shirou! There was one problem with the Godep.json file. It was trying to manage the telegraf repo itself as a dependency. I'm not sure how that happened but I rebased your changes and removed that. Thanks again!

**Comment by sparrc** [comment]
@shirou don't forget to sign up for Hacktoberfest! https://hacktoberfest.digitalocean.com/, between this and gopsutil you should be able to get a free t-shirt ;-D

**Pull request closed without merging**
