### PR TITLE
Godep update: gopsutil

### PR DESCRIPTION
**Pull request by sparrc**
cc @ranjib

### CODE REVIEW

**Comment by ranjib** [comment]
@sparrc this got overwritten by the procstat work :-( , master is now back to the old gopsutil revision

**Comment by sparrc** [comment]
@ranjib thanks for the heads up, I'll re-push

**Comment by ranjib** [comment]
also something is strange going on. https://github.com/shirou/gopsutil/commit/3303647209557312e5db51450ea8bbdef56d5176 shows the changes to arm related hosts utmp stuff, but the diffs here are different :-O

**Comment by sparrc** [comment]
oi vey, using godep always turns out to be more difficult than I expect, this may be because I previously had my origin set to influxdb/gopsutil instead of shirou/gopsutil

**Pull request merged**
