### PR TITLE
Lustre2 plugin

### PR DESCRIPTION
**Pull request by srfraser**
Lustre is a high performance cluster filesystem (http://lustre.org), used in HPC environments. Usefully, it makes data available in /proc, so here is a plugin to read those /proc files.

Lustre 2.x stores them in a different location to Lustre 1.x, hence the versioned plugin information. The configuration file allows those locations to be overridden for future proofing, and to make testing easier. 

One modification that may be necessary until cross-measurement mathematics is enabled is to store read_bytes and read_calls (and write_*) in the same measurement to get mean bytes per call metrics.

### CODE REVIEW

**Comment by srfraser** [comment]
Oh, one other remark: it uses ReadLines from system/ps/common/, to avoid code duplication. I'm unsure if that would be considered safe behaviour. It's tempting to move those common plugin utilities up a level for use across all plugins.

**Comment by sparrc** [comment]
Thanks for the contribution! Don't worry about the ReadLines piece, I will be refactoring all of that code to just use the external gopsutil library anyways

**Comment by sparrc** [comment]
@srfraser I can merge this once you've fixed the branch conflicts

**Comment by srfraser** [comment]
@sparrc Done - thank you!

**Pull request merged**
