### PR TITLE
Add net_bits_per_second_sent, net_bits_per_second_recv, net_packets_per_second_sent and net_packets_per_second_recv metrics to net plugin

### PR DESCRIPTION
**Pull request by SokoloffA**

### CODE REVIEW

**Comment by sparrc** [comment]
Thank you @SokoloffA, but this qualifies as a "derived metric" so I'm not going to merge it. You can calculate these using the InfluxDB `derivative()` function: https://influxdb.com/docs/v0.9/query_language/functions.html#derivative

**Comment by SokoloffA** [comment]
I understand, your want to reduce the amount of transfered and stored information. 
But for many people utilization more sensible than the number of transfered bytes. For example, if I have a SQL server, first of all I'm interested how my network card is utilized, but not how many bytes server transfered since last reboot. In truth, I'm not interested in traffic since the last reboot, maybe I would like to see how many bytes was sent during the last month or some day but not since the last reboot.
Is it possible to receive traffic for the period using bytes_sent? Say, how would look a query which will return the number of bytes sent during month? Is this data will correct, if server was rebooted in this period and counter was reseted?

Seems that the query will be not simple. it's no good, the system should be user-friendly out of the box. As Alan Kay said, "Simple things should be simple, complex things should be possible." Btw, I was not able to use the DERIVATIVE function in Grafana. I get an error "Error Response InfluxDB: error parsing query: aggregate function required inside the call to derivative".

We can get transferd bytes from bits_per_second using the SUM function. And IMO is more clearer.

I have a suggestion which everybody can agree. Each section in the configuration file should contain a list of the counters that the user wants to save. For example.

```
[net]
    interfaces = ["eth0"]

    bytes_sent = Off
    bytes_recv = Off
    packets_sent = Off
    packets_recv = Off
    err_in = On
    err_out = On
    drop_in = On
    drop_out = On
    bits_per_second_sent = On
    bits_per_second_recv = On
    packets_per_second_sent = On
    packets_per_second_recv = On
```

Then we can add a lot of different counters, and the user chooses what he wants to keep. One will save bytes_, another bits_per_second_. In addition this will allow us to reduce traffic and the amount of data compared with the current situation. Let's say I'm not interested in the counters of packages, and I can turn them off.

**Comment by sparrc** [comment]
That is a huge amount of configuration complication to add to every plugin. There are ways to query for everything you asked for. There is also a `non_negative_derivative` function which would ignore times when the server is rebooted.

I agree 100% that this needs to be documented better (welcome to open-source ;-)), I am working on a blog post on this exact subject of calculating "per-second" metrics from telegraf data.

For looking at historical data, of course this can also be queried using influxdb, I don't see how having the `per_second` measurements help you?

**Comment by sparrc** [comment]
see https://github.com/influxdb/influxdb/pull/2569

**Comment by SokoloffA** [comment]
Thanks for the advise about DERIVATIVE function. We can query this data, but it has restrictions:

 1. As I understand influxdb 0.9 does not support HAVING, so I won't be able to get the number of seconds when my card was loaded more 90%.
 2. It doesn't work in grafana. Yes it's a lack of grafana, not telegraf, and must be fixed. But in any case the user does not have one standard way to get base metrics of his system.
 3. NON_NEGATIVE_DERIVATIVE can miss data after rebooting, or to return incorrect data (less than really). 
 
It's perfect that influxdb allows to do complex queries, but complex queries should be used for complex analysis. I do not propose to abandon complex queries, and add all possible combinations of metrics. But there is a list of the metrics which are used everywhere and they should be available the easiest way. The standard workflow of administrators:

  1. install the program
  2. configure it
  3. regularly use queries of data

You simplify the second point, but make third hardes. The configuration is done once, but the requests will be made every day.

You wrote "that is a huge amount of configuration complication". I don't agree with you, the number of lines in the config will increase, but the complication will increase slightly. This is a very simple concept, there are metrics and we can enable/disable each of it. IMHO this concept is easier that current. If we look at CPU plugin, it has 3 settings

```
# Whether to report per-cpu stats or not
  percpu = true
# Whether to report total system cpu stats or not
  totalcpu = true
# Comment this line if you want the raw CPU time metrics
  drop = ["cpu_time"]
```

The novice will have to understand what these 3 settings are doing and how they are interrelated. In my solution, we have more lines, but all they do some - on or off one metric.

Again, many people are not interested in the details such User, System, Nice, Iowait, Irq, etc., they need one simple counter - how processor is busy. But we can't add such metric because it's "derived metric". As resul such guys must to store 10 times more data and query data from 10 columns.

**Comment by sparrc** [comment]
I don't disagree with you that it's a little more difficult to query for data via a derived metric. My problem is that it's bad database design to duplicate easily queryable data. For example, it would probably be easier to make a MySQL database without foreign keys but it sort of defeats the purpose of using a relational database in the first place.

Rate of change metrics are something I'll need to talk with other people here at Influx about, the general idea so far has been that people should use the DERIVATIVE function, but if there are compelling problems that the DERIVATIVE functions can't solve then we may need to revisit this.

Re: innacurate NON_NEGATIVE_DERIVATIVE, if that's true you should open an issue against influxdb, it shouldn't be inaccurate. I'm not sure what you mean by it dropping data on reboot, the whole point is that it drops the one point at which the derivative is negative, how else could a reboot of a counter be handled?

Re: HAVING, can you explain how derived metrics help with this problem?

Re: Having a config file parameter for every single metric. This is an absolute no, this is the whole point of the plugin drop/pass configuration options: https://github.com/influxdb/telegraf#plugin-options

Re: CPU plugin, there is no reason to sum all of those metrics, it's simple to get busy percentage: `100 - cpu_usage_idle`

**Comment by SokoloffA** [comment]
>Having a config file parameter for every single metric. This is an absolute no, this is the whole point of the plugin drop/pass configuration options: https://github.com/influxdb/telegraf#plugin-options

I was confused, sample config for net plugin has no mention about drop/pass. OK, if we have a drop/pass configuration options that prevents us to add my metrics and disable them by default? 
I do not propose to store all the metrics I propose to give the user a choice.

>HAVING, can you explain how derived metrics help with this problem?

I have the following data:

```
> select value from net_bits_per_second_sent where time > '2015-10-04 06:10:00' and time < '2015-10-04 06:10:05'
name: net_bits_per_second_sent
------------------------------
time                    value
2015-10-04T06:10:01Z    226296
2015-10-04T06:10:02Z    227824
2015-10-04T06:10:03Z    227128
2015-10-04T06:10:04Z    233976
```

I can query bytes per second

```
> SELECT derivative(value , 1s) * 8 FROM "net_bytes_sent" WHERE time > '2015-10-04 06:10:00' - 1s and time < '2015-10-04 06:10:05'
name: net_bytes_sent
--------------------
time
2015-10-04T06:10:01Z    226112
2015-10-04T06:10:02Z    227840
2015-10-04T06:10:03Z    227304
2015-10-04T06:10:04Z    233904
```

But I can't filter it, say get rows where bytes per second more than 230000, I tried following without success
```
SELECT derivative(value , 1s) * 8 FROM "net_bytes_sent" WHERE value > 230000 and time > '2015-10-04 06:10:00' - 1s and time < '2015-10-04 06:10:05'
SELECT derivative(value , 1s) * 8 FROM "net_bytes_sent" WHERE value > 1840000 and time > '2015-10-04 06:10:00' - 1s and time < '2015-10-04 06:10:05'
SELECT derivative(value , 1s) * 8 as v FROM "net_bytes_sent" WHERE v > 230000 and time > '2015-10-04 06:10:00' - 1s and time < '2015-10-04 06:10:05'
```
HAVING not supported too.

With my metrics is trivial
```
> select value from net_bits_per_second_sent where value > 230000 and time > '2015-10-04 06:10:00' and time < '2015-10-04 06:10:05'
name: net_bits_per_second_sent
------------------------------
time                    value
2015-10-04T06:10:04Z    233976
```

**Comment by sparrc** [comment]
@SokoloffA thanks that makes more sense now, let me talk to the other Influx people and see what they think

**Comment by cornerot** [comment]
> Seems that the query will be not simple. it's no good, the system should be user-friendly out of the box. As Alan Kay said, "Simple things should be simple, complex things should be possible." Btw, I was not able to use the DERIVATIVE function in Grafana. I get an error "Error Response InfluxDB: error parsing query: aggregate function required inside the call to derivative".

You can use custom query in graphana:

```SELECT derivative(value) FROM "net_bytes_recv" WHERE "name" = 'dev-vm' AND "interface" = 'eth0'```

instead of:

```SELECT derivative(value) FROM "net_bytes_recv" WHERE "name" = 'dev-vm' AND "interface" = 'eth0' AND $timeFilter GROUP BY time($interval)```

**Comment by sparrc** [comment]
@SokoloffA I'm going to close this PR as we won't be merging it without more deliberation. You should be able to solve your issue using continuous queries: https://influxdb.com/docs/v0.9/query_language/continuous_queries.html, and there are also meta-queries coming that will allow something like `SELECT {SELECT derivative(value) FROM net_bytes_recv} as result WHERE result > 90`

**Pull request closed without merging**
