### PR TITLE
package.sh: upload raw binaries to S3

### PR DESCRIPTION
**Pull request by sparrc**
/cc @beckettsean @gunnaraasen how do we feel about distributing linux binaries of telegraf? I was thinking that this might be good for people who want to try out telegraf without installing a .deb or .rpm which also installs an init service on the server.

Also nice for people who just want to manage the service themselves

### CODE REVIEW

**Comment by gunnaraasen** [comment]
Sounds good to me. I think there was a request for something similar for InfluxDB but I can't find the issue.

**Comment by beckettsean** [comment]
Let's do it. We get requests for binaries for chronograf and influxdb fairly frequently, it's just a matter of time for telegraf.

**Comment by sparrc** [comment]
great! will also probable need an influxdb.com update for the downloads page, they'll start getting uploaded with 0.1.8

**Comment by beckettsean** [comment]
I added a note to https://github.com/influxdb/influxdb.com/issues/267 to document the telegraf tarball, too.

**Comment by sparrc** [comment]
Cool, I'll update this PR to actually tar -zcf the binary rather than zip, just for consistency with the DB

**Comment by beckettsean** [comment]
@sparrc agreed. I think gzipped tarballs are more standard than just gzipped files.

**Pull request merged**
