### PR TITLE
[WIP] snmp plugin

### PR DESCRIPTION
**Pull request by titilambert**
Hello,
This is my first plugin and my first code using go ... So I accept all feedback :)
This plugin handles snmpget and snmpgetbulk.
I will use it to monitoring local applications which expose data using SNMP protocol.

Thanks for your feedback.

TODO:
* test
* cleaning

### CODE REVIEW

**Comment by titilambert** [comment]
Should I copy config format from collectd: https://collectd.org/wiki/index.php/Plugin:SNMP ?

**Comment by sparrc** [comment]
@titilambert probably not good to model it after collectd, I like the configuration of https://github.com/paulstuart/influxsnmp, which uses a file that the user generates via `snmptranslate`, would that be plausible.

**Comment by titilambert** [comment]
Hello @sparrc !
About MIBs, I added it. I use snmptranslate command, to get translate oids=>name. All translations will be cached at the first run :)
I changed the configuration to format. I think the format is more flexible and simple.

**Comment by titilambert** [comment]
@sparrc How can I relaunch test ? It failed cause download error :/

**Comment by sparrc** [comment]
I kicked a rebuild, do you see a rebuild button in the upper-right from the "Details" link?

**Comment by titilambert** [comment]
@sparrc I'm not seeing anything :/ even logged in... Maybe can't because I'm not developer in telegraf ?
Anyway, Thanks!

**Comment by sparrc** [comment]
@titilambert why did you close this PR?

**Comment by titilambert** [comment]
@sparrc oups ! I will reopen it using an other branch

**Comment by titilambert** [comment]
New PR is here #453

**Pull request closed without merging**
